aintainer        "firma...."
maintainer_email  "cookbooks@opscode.com"
license           "Apache 2.0"
description       "social mitfahrzentrale"
version           "0.9"
recipe            "mitfahrapp::deploy", "Main Apache configuration"